### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by harishreddy-m** [kadirahq/meteor-login-state#11]
You are setting a cookie on successful login.
I don't see any code where you are making use of that cookie to login into second meteor app.

Can you please help me in finding the code where you make use of the cookie you created on successful login in first meteor app.

**Comment by steven-tib** [comment]
@harishreddy-m have you managed to make it work as you want ? I saw that you were trying to share the login state between your app and rocket-chat, this is exactly what I'm trying to do, if you found a solution I would be happy to know it. thank you

**Comment by harishreddy-m** [comment]
@steven-tib Yes.I was able to achieve this objective.But with a [different package](https://github.com/jfrolich/meteor-subdomain-persistent-login) - not this one.

Even after that there was conflict in roles as my application was using [groups](https://github.com/alanning/meteor-roles#roles-groups), rocket chat is using array of strings as roles.
So,I forked alanning:roles and made it to use a different key for storing roles for my application.

Then it worked.

**Comment by steven-tib** [comment]
Thanks for your help @harishreddy-m in the meantime I also found the same package and finally got it working. I have another configuration and use two separate database (one for the chat, one for the main app) so I don't have the issue with roles (but actually I have other "syncing" issues, to keep the user accounts up to date on both db).

**Comment by harishreddy-m** [comment]
How are you syncing?
Event-driven or cron job?

**Comment by steven-tib** [comment]
I'm using hooks on new user created and user updates from the main-app
side, it reproduces the changes directly in the chat database (using remote
mongo connection).
I have the feeling that it's a lot of workarounds right now, but I'm trying
to find a way to consolidate it with the API.
I just struggle to login using the hash password given by the
´Accounts.onLogin´ event with the api/v1/login.. maybe I'm doing something
wrong but this would solve a lot of my workarounds and avoid writing
directly in the remote chat DB, and therfore avoid being inconsistant by
bypassing the real update/create methods from the chat app...

Are you using the API login for any calls ?

To come back to the syncing of login state:
how do you login automatically on the chat once you shared the tokens and
uerId trough the subdomain cookie ? is it happening automatically as you
share the exact same db ?

On my side, in the chat-app, I have to use ´accounts.loginWithTokens()´
function after reading those cookies, all of this in a ´meteor.startup´ so
it happens on page load directly.
but prior to that, I have to sync the ´resume.loginTokens´ from my main-app
so the loginWithTokens function works properly. a bit complicated ... but
it works so far.



2016-12-19 3:54 GMT+01:00 Harish Reddy <notifications@github.com>:

> How are you syncing?
> Event-driven or cron job?
>

**Comment by steven-tib** [comment]
I'm using hooks on new user created and user updates from the main-app
side, it reproduces the changes directly in the chat database (using remote
mongo connection).

I have the feeling that it's a lot of workarounds right now, but I'm trying
to find a way to consolidate it with the API.
I just struggle to login using the hash password given by the
`Accounts.onLogin` event with the api/v1/login.. maybe I'm doing something
wrong but this would solve a lot of my workarounds and avoid writing
directly in the remote chat DB, and therfore avoid being inconsistant by
bypassing the real update/create methods from the chat app...

Are you using the API login for any calls ?

To come back to the login state syncing, I have other questions: 
how do you login automatically on the chat once you shared the tokens and
userId trough the subdomain cookie ? is it happening automatically when you load the page as you
share the exact same db ?

On my side, in the chat-app, I have to use `accounts.loginWithTokens()`
function after reading those cookies, all of this in a ´meteor.startup´ so
it happens on page load directly.
but prior to that, I have to sync the `resume.loginTokens` from my main-app
so the loginWithTokens function works properly. 
a bit complicated ... but it works so far.

**Comment by harishreddy-m** [comment]
>  is it happening automatically when you load the page as you
share the exact same db ?

Yes

> Are you using the API login for any calls ?

No

**Comment by steven-tib** [comment]
@harishreddy-m may I ask you to share your fork of alaning-roles that is compatible with Rocket chat roles' structure? maybe can you publish it on atmosphere ?
I would like to try out your solution as mine is pretty unstable and slow right now...

**Comment by harishreddy-m** [comment]
@steven-tib 
I informed my senior about this.Once he approves I can share it with you.
