### ISSUE TITLE
Add LoginState.get script to Meteor client?

### ISSUE THREAD

**Issue by jadsonlourenco** [kadirahq/meteor-login-state#2]
Why not add the script: https://github.com/kadirahq/meteor-login-state/blob/master/includes/login_state.js for meteor app, on client side, in this case we can use the function "LoginState.get", without need to create manually.

**Comment by arunoda** [comment]
Good idea.
@thinkholic could you add this feature.

**Comment by thinkholic** [comment]
@jadsonlourenco added. now it can simply call by using `LoginState.get(<cookieName>)`.

**Comment by jadsonlourenco** [comment]
@thinkholic @arunoda Yes, I see it now, thank you!
